import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Fastify from 'fastify';
import sharp from 'sharp';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { registerRoutes } from '../src/api/routes';
import { sha256 } from '../src/assets/manifest';

describe('published generated asset routes', () => {
  let root: string;
  let gameDir: string;
  let app: ReturnType<typeof Fastify>;
  let keyArt: Buffer;

  beforeEach(async () => {
    root = mkdtempSync(join(tmpdir(), 'sparkade-generated-route-'));
    gameDir = join(root, 'game');
    const assetsDir = join(gameDir, 'assets');
    mkdirSync(assetsDir, { recursive: true });
    writeFileSync(join(assetsDir, 'portrait.png'), 'legacy portrait');
    keyArt = await sharp({
      create: { width: 64, height: 48, channels: 3, background: '#643c8f' },
    })
      .png()
      .toBuffer();
    writeFileSync(join(assetsDir, 'key-art.png'), keyArt);
    // A known compiled filename is still private until a manifest declares it.
    writeFileSync(join(assetsDir, 'story-intro.png'), 'unmanifested story art');
    writeFileSync(
      join(assetsDir, 'manifest.json'),
      JSON.stringify({
        version: 1,
        assets: [
          {
            role: 'keyArt',
            filename: 'key-art.png',
            mimeType: 'image/png',
            width: 64,
            height: 48,
            model: 'muse-image-1.0',
            promptVersion: 'key-art-v1',
            promptSha256: sha256('key-art prompt'),
            sha256: sha256(keyArt),
          },
        ],
      }),
    );

    app = Fastify();
    const row = { id: 'game-1', jobId: null };
    registerRoutes(app, {
      db: {
        getGame: (id: string) => (id === 'game-1' ? row : null),
        listItem: () => ({ id: 'game-1', cover: null }),
        usageForGame: () => [],
      } as never,
      files: {
        gameDir: () => gameDir,
        readSpec: () => null,
        readMeta: () => null,
      } as never,
      configStore: {} as never,
      runner: {} as never,
      hub: {} as never,
      version: 'test',
      instanceId: 'test-instance',
      port: 0,
    });
  });

  afterEach(async () => {
    await app.close();
    rmSync(root, { recursive: true, force: true });
  });

  it('reports manifest-backed generated assets and every fighter pose flag', async () => {
    const response = await app.inject({ method: 'GET', url: '/api/games/game-1' });

    expect(response.statusCode).toBe(200);
    const assets = response.json().assets as Record<string, boolean>;
    expect(assets.portrait).toBe(false);
    expect(assets.keyArt).toBe(true);
    expect(assets.storyIntro).toBe(false);
    expect(Object.keys(assets).filter((name) => name.startsWith('fighter'))).toHaveLength(11);
    expect(
      Object.entries(assets)
        .filter(([name]) => name.startsWith('fighter'))
        .every(([, available]) => !available),
    ).toBe(true);
  });

  it('serves manifest-declared PNGs and fails closed for undeclared legacy files', async () => {
    const [legacy, generated] = await Promise.all([
      app.inject({ method: 'GET', url: '/api/games/game-1/assets/portrait.png' }),
      app.inject({ method: 'GET', url: '/api/games/game-1/assets/key-art.png' }),
    ]);

    expect(legacy.statusCode).toBe(404);
    expect(generated.statusCode).toBe(200);
    expect(generated.headers['content-type']).toBe('image/png');
    expect(generated.rawPayload.equals(keyArt)).toBe(true);
  });

  it('continues serving likeness files for legacy games without a manifest', async () => {
    rmSync(join(gameDir, 'assets', 'manifest.json'));

    const legacy = await app.inject({
      method: 'GET',
      url: '/api/games/game-1/assets/portrait.png',
    });

    expect(legacy.statusCode).toBe(200);
    expect(legacy.headers['content-type']).toBe('image/png');
    expect(legacy.body).toBe('legacy portrait');
  });

  it('fails closed when published generated bytes no longer match the manifest', async () => {
    writeFileSync(join(gameDir, 'assets', 'key-art.png'), 'tampered bytes');

    const [details, generated] = await Promise.all([
      app.inject({ method: 'GET', url: '/api/games/game-1' }),
      app.inject({ method: 'GET', url: '/api/games/game-1/assets/key-art.png' }),
    ]);

    expect(details.statusCode).toBe(200);
    expect((details.json().assets as Record<string, boolean>).keyArt).toBe(false);
    expect(generated.statusCode).toBe(404);
  });

  it('denies unmanifested generated filenames and the manifest itself', async () => {
    const [unmanifested, manifest] = await Promise.all([
      app.inject({ method: 'GET', url: '/api/games/game-1/assets/story-intro.png' }),
      app.inject({ method: 'GET', url: '/api/games/game-1/assets/manifest.json' }),
    ]);

    expect(unmanifested.statusCode).toBe(404);
    expect(manifest.statusCode).toBe(404);
  });
});
