// Racing archetype core (milestone 3: schema + GameHost integration).
//
// A reusable deterministic hover-racing core: three handcrafted closed
// circuits, shared player/AI physics, boost/pads/offroad/barriers,
// cheat-proof lap gates, positions, finish/restart, cup points, timeout/DNF,
// a RacingSpec schema + lint + golden game, and a behind-vehicle Canvas2D
// renderer with per-circuit themes plus a host HUD-hook overlay pass.
// Registered in the archetype registry; the creation wizard keeps its own
// curated list, so generation-pipeline exposure stays a separate milestone.
export { racing } from './archetype';
export {
  HoverEngine,
  type HoverEngineCaps,
  type HoverEngineState,
  type HoverEngineStatus,
} from './audio';
export { lintRacing, estimateRacingDurationS, RACING_ESTIMATE_SPEED } from './lint';
export {
  analyzeBends,
  nextBend,
  bannerStale,
  boardChevrons,
  boardsFor,
  nearestRival,
  positionEvent,
  playerPos,
  UNITS_TO_M,
  SWEEP_CURVE,
  SHARP_CURVE,
  TIGHT_CURVE,
  BOARD_OFFSETS,
  POS_EVENT_COOLDOWN,
  type Bend,
  type BendSeverity,
  type Upcoming,
  type RivalGap,
} from './feedback';
export {
  TIMING_VERSION,
  TIMING_GATES,
  FIRST_FLYING_LAP,
  MAX_CACHED_RECORDS,
  geometrySignature,
  recordKey,
  validateBest,
  memoryStore,
  localStorageStore,
  PersonalBests,
  LapAttempt,
  formatDelta,
  type PersonalBest,
  type BestStore,
  type LapSample,
  type AttemptResult,
} from './timing';
export {
  createRacingGame,
  gameIdentity,
  projectRoad,
  projectAtZ,
  turnCueAt,
  resolveCupRaces,
  truncateName,
  cupCraftColors,
  CUP_RACE_COUNT,
  CUP_COUNTDOWN,
  RACING_CONTROLS,
  RACING_FOCAL,
  RACING_CAM_H,
  RACING_CAM_BACK,
  RACING_Z_NEAR,
  RACING_Z_SPAN,
  RACING_HORIZON,
  RACING_SEGMENTS,
  RACING_SEG_LEN,
  CRAFT_WORLD_W,
  type Projected,
  type ResolvedCupRace,
  type RacingCupPhase,
  type RacingDevSnapshot,
  type RacingDevHandle,
} from './game';
export {
  PANORAMA_SOURCE_HEIGHT,
  PANORAMA_SOURCE_WIDTH,
  PANORAMA_SOURCE_Y,
  ROAD_TILE_WORLD,
  STRIP_BODY_FILL,
  authoredPalette,
  craftPoseSourceX,
  depthShade,
  exhaustFlame,
  fitTileWorld,
  groundSourceSpans,
  hexRgb,
  isLandmarkSlot,
  makeArtSpriteQueue,
  materialTileRect,
  panoramaMaxOffset,
  panoramaPlateHeight,
  panoramaSourceX,
  perspectiveZ,
  resolveRaceArt,
  rowAtlasRow,
  sampleStripRow,
  scaleRgb,
  sceneryAtlasCell,
  scenerySlotFor,
  selectCraftPose,
  sortArtSprites,
  stableRosterNames,
  stripSourceRuns,
  withAlpha,
  worldTilePhase,
  type ArtSprite,
  type GroundSpan,
  type RaceArtRefs,
  type SourceRun,
} from './art';
export {
  createRace,
  createRaceFor,
  restartRace,
  stepRace,
  stepRacer,
  aiInputFor,
  racePosition,
  playerResult,
  classifyRace,
  createCup,
  recordRaceResult,
  cupStandings,
  cupComplete,
  restartCup,
  isPickupTaken,
  pickupsRemaining,
  pickupTargetX,
  RACE_LAPS,
  RACER_COUNT,
  PLAYER_INDEX,
  PLAYER_TOP_SPEED,
  PICKUP_YIELD,
  PICKUP_TRICKLE,
  CUP_POINTS,
  DEFAULT_CIRCUIT_INDEX,
  makeRacer,
  type RaceState,
  type RacerInput,
  type RacerState,
  type ClassifiedEntry,
  type CupState,
} from './simulation';
export {
  TRACK_LENGTH,
  ROAD_HALF,
  CURB_WIDTH,
  PAD_HALF_X,
  PICKUP_HALF_X,
  PICKUP_COUNT,
  BARRIER_X,
  CHECKPOINT_FRACTIONS,
  BOOST_PADS,
  RACE_CIRCUITS,
  compileTrack,
  compileTrackVariant,
  mirrorPoints,
  auditCircuit,
  wrapS,
  curvatureAt,
  headingAt,
  pointAt,
  tangentAt,
  trackOutlinePoints,
  padAt,
  pickupsFor,
  type CompiledTrack,
  type TrackPoint,
  type BoostPad,
  type EnergyPickup,
  type CircuitTheme,
  type CircuitTemplateDef,
  type RaceCircuit,
  type CircuitAudit,
} from './track';
