// Racing archetype core (milestone 3: schema + GameHost integration).
//
// A reusable deterministic hover-racing core: three handcrafted closed
// circuits, shared player/AI physics, boost/pads/offroad/barriers,
// cheat-proof lap gates, positions, finish/restart, cup points, timeout/DNF,
// a RacingSpec schema + lint + golden game, and a behind-vehicle Canvas2D
// renderer with per-circuit themes plus a host HUD-hook overlay pass.
// Registered in the archetype registry; the creation wizard keeps its own
// curated list, so generation-pipeline exposure stays a separate milestone.
export { racing } from './archetype';
export {
  HoverEngine,
  type HoverEngineCaps,
  type HoverEngineState,
  type HoverEngineStatus,
} from './audio';
export { lintRacing, estimateRacingDurationS, RACING_ESTIMATE_SPEED } from './lint';
export {
  analyzeBends,
  nextBend,
  bannerStale,
  boardChevrons,
  boardsFor,
  nearestRival,
  positionEvent,
  playerPos,
  UNITS_TO_M,
  SWEEP_CURVE,
  SHARP_CURVE,
  TIGHT_CURVE,
  BOARD_OFFSETS,
  POS_EVENT_COOLDOWN,
  type Bend,
  type BendSeverity,
  type Upcoming,
  type RivalGap,
} from './feedback';
export {
  TIMING_VERSION,
  TIMING_GATES,
  FIRST_FLYING_LAP,
  MAX_CACHED_RECORDS,
  geometrySignature,
  recordKey,
  validateBest,
  memoryStore,
  localStorageStore,
  PersonalBests,
  LapAttempt,
  formatDelta,
  type PersonalBest,
  type BestStore,
  type LapSample,
  type AttemptResult,
} from './timing';
export {
  createRacingGame,
  gameIdentity,
  projectRoad,
  projectAtZ,
  turnCueAt,
  resolveCupRaces,
  truncateName,
  craftLean,
  clampVisRoll,
  poseBankThreshold,
  offroadLabel,
  helpControlsLine,
  VIS_ROLL_MAX,
  type CraftLean,
  cupCraftColors,
  CUP_RACE_COUNT,
  CUP_COUNTDOWN,
  RACING_CONTROLS,
  RACING_FOCAL,
  RACING_CAM_H,
  RACING_CAM_BACK,
  RACING_Z_NEAR,
  RACING_Z_SPAN,
  RACING_HORIZON,
  RACING_SEGMENTS,
  RACING_SEG_LEN,
  CRAFT_WORLD_W,
  type Projected,
  type ResolvedCupRace,
  type RacingCupPhase,
  type RacingDevSnapshot,
  type RacingDevHandle,
} from './game';
export {
  PANORAMA_SOURCE_HEIGHT,
  PANORAMA_SOURCE_WIDTH,
  PANORAMA_SOURCE_Y,
  ROAD_TILE_WORLD,
  STRIP_BODY_FILL,
  authoredPalette,
  craftPoseSourceX,
  depthShade,
  exhaustFlame,
  fitTileWorld,
  groundSourceSpans,
  hexRgb,
  isLandmarkSlot,
  makeArtSpriteQueue,
  materialTileRect,
  PANORAMA_BLEND_OVERLAP,
  panoramaBlendWeight,
  panoramaMaxOffset,
  panoramaPeriodWidth,
  panoramaPlateHeight,
  panoramaSliceSpans,
  panoramaSourceX,
  perspectiveZ,
  resolveRaceArt,
  packCraftSource,
  bakedPoseLean,
  BAKED_POSE_LEAN,
  selectCraftPoseSteady,
  POSE_HYSTERESIS,
  packResidualLean,
  VIS_LEAN_MAX,
  rowAtlasRow,
  sampleStripRow,
  scaleRgb,
  sceneryAtlasCell,
  scenerySlotFor,
  selectCraftPose,
  sortArtSprites,
  stableRosterNames,
  stripSourceRuns,
  withAlpha,
  worldTilePhase,
  type ArtSprite,
  type GroundSpan,
  type PackCraftSource,
  type PanoramaSlice,
  type RaceArtRefs,
  type SourceRun,
} from './art';
export {
  createRace,
  createRaceFor,
  restartRace,
  stepRace,
  stepRacer,
  aiInputFor,
  isAirborne,
  racePosition,
  playerResult,
  classifyRace,
  createCup,
  recordRaceResult,
  cupStandings,
  cupComplete,
  restartCup,
  isPickupTaken,
  pickupsRemaining,
  pickupTargetX,
  RACE_LAPS,
  RACER_COUNT,
  PLAYER_INDEX,
  PLAYER_TOP_SPEED,
  PICKUP_YIELD,
  PICKUP_TRICKLE,
  CUP_POINTS,
  DEFAULT_CIRCUIT_INDEX,
  makeRacer,
  type RaceState,
  type RacerInput,
  type RacerState,
  type RacerAirState,
  type ClassifiedEntry,
  type CupState,
} from './simulation';
export {
  JUMP_AIRBORNE_HEIGHT,
  JUMP_AIR_STEER_SCALE,
  JUMP_COOLDOWN,
  JUMP_CURVE_MAX,
  JUMP_FRACTIONS,
  JUMP_GRAVITY,
  JUMP_IMPULSE_MAX,
  JUMP_IMPULSE_MIN,
  JUMP_KEEPOUT,
  JUMP_LANDING_CUE,
  JUMP_RAMP_HALF_WIDTH,
  JUMP_RAMP_LENGTH,
  JUMP_RAMP_X,
  JUMP_SEARCH_HALF,
  JUMP_TAKEOFF_MIN_SPEED,
  jumpImpulseFor,
  jumpLayoutKey,
  jumpLipS,
  jumpZoneContains,
  rampsFor,
  resolveJumps,
  type JumpRamp,
} from './jumps';
export {
  FORK_CURVE_MAX,
  FORK_CURVE_MARGIN,
  FORK_ENTER,
  FORK_EXIT,
  FORK_FRACTION,
  FORK_ISLAND_HALF,
  FORK_KEEPOUT,
  FORK_LEFT_CENTER,
  FORK_OUTER_L,
  FORK_OUTER_R,
  FORK_RAMP_KEEPOUT,
  FORK_RIGHT_CENTER,
  FORK_SHOULDER,
  FORK_ZONE,
  applyForkSupplies,
  clampForkX,
  forkBranchSide,
  forkCenterS,
  forkCrossSection,
  forkFor,
  forkLayoutKey,
  resolveForks,
  type ForkLayout,
  type ForkSection,
  type RacingForks,
} from './forks';
export {
  HOVER_MOVEMENT,
  JETSKI_MOVEMENT,
  boundaryCapTop,
  movementFor,
  movementForTraversal,
  resolveDiscipline,
  type MovementProfile,
} from './movement';
export {
  LEGACY_PRESENTATION,
  accelWordFor,
  flameForPresentation,
  helpControlsLineFor,
  isWaterCircuit,
  racingControlsFor,
  resolveRacePresentation,
  riderBobFor,
  slideWordFor,
  speedScaleFor,
  speedTextFor,
  surfaceDisciplineFor,
  surfaceForCircuit,
  titleLabelFor,
  trailForPresentation,
  type RacePresentation,
} from './presentation';
export {
  BICYCLE_TRAVERSAL,
  MAGIC_BOARD_TRAVERSAL,
  MOTORCYCLE_TRAVERSAL,
  RACING_HANDLINGS,
  RACING_PROPULSIONS,
  RACING_RIDERS,
  RACING_SURFACES,
  SKATEBOARD_TRAVERSAL,
  TRAVERSAL_HANDLING_TUNINGS,
  handlingTuningFor,
  resolveTraversal,
  type RacingHandling,
  type RacingHandlingTuning,
  type RacingPropulsion,
  type RacingRider,
  type RacingSurface,
  type RacingTraversal,
} from '@sparkade/shared';
export {
  TRACK_LENGTH,
  ROAD_HALF,
  CURB_WIDTH,
  PAD_HALF_X,
  PICKUP_HALF_X,
  PICKUP_COUNT,
  BARRIER_X,
  CHECKPOINT_FRACTIONS,
  BOOST_PADS,
  RACE_CIRCUITS,
  compileTrack,
  compileTrackVariant,
  mirrorPoints,
  auditCircuit,
  wrapS,
  curvatureAt,
  headingAt,
  pointAt,
  tangentAt,
  trackOutlinePoints,
  padAt,
  pickupsFor,
  type CompiledTrack,
  type TrackPoint,
  type BoostPad,
  type EnergyPickup,
  type CircuitTheme,
  type CircuitTemplateDef,
  type RaceCircuit,
  type CircuitAudit,
} from './track';
export {
  RIDGE_PROFILE,
  ROLLING_PROFILE,
  elevationGrade,
  elevationHeight,
  elevationProfileFor,
  resolveElevation,
  trackGradeAt,
  trackHeightAt,
  type ElevatedKind,
  type ElevationProfile,
  type Elevatable,
} from './elevation';
